package exceptionHandling;

import java.io.InputStream;
import java.util.InputMismatchException;
import java.util.Scanner;

public class testException {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		try{
		Scanner s=new Scanner(System.in);
		int a=s.nextInt();
		int b=s.nextInt();
		System.out.println(a/b);
		}
		catch(InputMismatchException | ArithmeticException e)
		{
			if(e.getClass().getName().equals("InputMismatchException"))
			System.out.println("Entered input is not a number");
		
			if(e.getClass().getName().equals("ArithmeticException"))
				System.out.println("Division by zero is not allowed");
			
		}
	}

}
